{% set name = "price-parser" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/price-parser-{{ version }}.tar.gz
  sha256: 8a286caa40fe28912f5e596bf09d72e085f80c4b2acaf5dd22aab8298e6ba731

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - attrs >=17.3.0

test:
  imports:
    - price_parser
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/scrapinghub/price-parser
  summary: Extract price and currency from a raw string
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - muyajil
